# Generated by Django 4.2.4 on 2023-08-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='study_move_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_move_volume',
            field=models.IntegerField(default=0),
        ),
    ]
