# Generated by Django 4.2.4 on 2023-08-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_study_study_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
