# Generated by Django 4.2.4 on 2023-08-24 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weekdayStudy', '0003_remove_weekdaystudy_study_type'),
        ('core', '0006_rename_study_date_study_study_date_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.DeleteModel(
            name='StudyType',
        ),
        migrations.AddField(
            model_name='study',
            name='study_type',
            field=models.CharField(choices=[('weekday_study', 'WEEKDAY STUDY - Analyzes how a stock moves daily on any day of the week.'), ('gap_study', 'GAP STUDY - Analyzes continuation gaps of a stock on a given day'), ('move study', 'MOVE STUDY - Analyzes non-gap stock price movements on a given day'), ('fundamentals_study', 'FUNDAMENTAL SNAPSHOT - Company SEC 10q fundamentals, rates of growth, and forecast for a specific date'), ('ep_study', 'EPISODIC PIVOT - there can be only one')], default='weekday_study', max_length=32),
        ),
        migrations.AddField(
            model_name='message',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.study'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
