# Generated by Django 4.2.4 on 2023-08-24 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekdayStudy', '0002_weekdaystudy_chg_from_yest_count_down_friday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekdaystudy',
            name='study_type',
        ),
    ]
