# Generated by Django 5.2.2 on 2025-07-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='study_type',
            field=models.CharField(choices=[('long_term_value', 'Long Term Value - Buy and hold for months or years'), ('growth_investing', 'Growth Investing - Holding higher growth and momentum stocks'), ('long_term_value', 'Swing Trading - Hold periods of weeks to months')], default='long_term_value', max_length=32),
        ),
    ]
