# Generated by Django 5.2.2 on 2025-07-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_tag_portfolio_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='study_type',
            new_name='portfolio_type',
        ),
    ]
