# Generated by Django 5.2.2 on 2025-08-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_alter_review_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created']},
        ),
    ]
