# Generated by Django 5.2.2 on 2025-07-30 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_rename_study_type_portfolio_portfolio_type'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_type',
            field=models.CharField(choices=[('Long term value investing', 'Long Term Value - Buy and hold for months or years'), ('Growth investing, short to long term', 'Growth Investing - Holding higher growth and momentum stocks'), ('Swing trade, short term', 'Swing Trading - Hold periods of weeks to months')], default='Long term value investing', max_length=200),
        ),
    ]
